apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/jump-app-cicd/back-springboot:develop
        imagePullPolicy: Always
        name: back-springboot-v1
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
        resources: {}
        env:  
          - name: APP_REF_NAME
            value: jump-app