apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: front-javascript
configMapGenerator:
  - name: react-envs
    literals:
      - REACT_APP_BACK=https://back-golang-public/jump
      - REACT_APP_GOLANG=http://back-golang:8442
      - REACT_APP_PYTHON=http://back-python:8444
      - REACT_APP_SPRINGBOOT=http://back-springboot:8443
