apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: front-javascript
configMapGenerator:
  - name: react-envs
    envs:
    - application.properties
