apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-golang
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/jump-app-cicd/back-golang:develop
        imagePullPolicy: Always
        name: back-golang
        ports:
          - containerPort: 8442
            protocol: TCP
        resources: {}
        env:  
          - name: APP_REF_NAME
            value: jump-app