apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: back-springboot
spec:
  gateways:
  - back-springboot
  - mesh
  hosts:
  - back-springboot
  http:
  - route:
      - destination:
          host: back-springboot
        weight: 100